#! python3
# grand_gap_filler - program to correct gaps in file numbering

import re
import os

DIRECTORY = 'C:\\Users\\A\Google Drive\\OP2\\TestFolder'
#DIRECTORY = '/Users/A/Google Drive/OP2'



def put_files_in_sorted_list(folder):
    sorted_filename_list = sorted(os.listdir(folder))
    print(sorted_filename_list)
    return sorted_filename_list

def get_list_of_ints(sorted_file_list):
    sorted_file_str = ''.join(sorted_file_list)
    filename_digits_str = re.findall(r'\d+', sorted_file_str)
    filename_int_list = [int(elem) for elem in filename_digits_str]
    print('filename_digits_int >> ' + str(filename_int_list))
    return filename_int_list

def get_correct_sequence_numbering(filename_int_list):
    corrected_values_after_enumerate = []
    for counter, value in enumerate(filename_int_list, filename_int_list[0]):
        print('counter >> ' + str(counter))
        print('value >> ' + str(value))
        if counter != value:
            value = counter
            corrected_values_after_enumerate.append(value)
            print('Corrected value to %s' % (str(value)))
        else:
            corrected_values_after_enumerate.append(value)                       
    print('corrected list after enumerate >> ' + str(corrected_values_after_enumerate))
    return corrected_values_after_enumerate
        
def replace_file_names(sorted_file_list, corrected_values_after_enumerate):
    updated_filename_list = []
    for filename, element in zip(sorted_file_list, corrected_values_after_enumerate):
        print('filename %s element %s' % (filename, str(element)))
        #element_length = len(str(element))
        updated_filename_list_entry = re.sub(r'(\d+)', str(element), filename)
        print(updated_filename_list_entry)
        updated_filename_list.append(updated_filename_list_entry)
    return updated_filename_list


#Todo: change actual file names

sorted_filename_list = put_files_in_sorted_list(DIRECTORY)
filename_int_list = get_list_of_ints(sorted_filename_list)
corrected_values_after_enumerate = get_correct_sequence_numbering(filename_int_list)
print(sorted_filename_list)
updated_filename_list = replace_file_names(sorted_filename_list, corrected_values_after_enumerate)
print(updated_filename_list)
