#! python3
# grand_gap_filler - program to correct gaps in file numbering

import re
import os

DIRECTORY = 'C:\\Users\\A\Google Drive\\OP2\\TestFolder'

def put_files_in_sorted_list(folder):
    sorted_file_list = sorted(os.listdir(folder))
    print(sorted_file_list)
    return sorted_file_list

def get_list_of_ints(sorted_file_list):
    sorted_file_str = ''.join(sorted_file_list)
    filename_digits_str = re.findall(r'\d+', sorted_file_str)
    filename_int_list = [int(elem) for elem in filename_digits_str]
    print('filename_digits_int >> ' + str(filename_int_list))
    return filename_int_list

def get_correct_sequence_numbering(input_list):
    seed = input_list[0]
    print('seed: ' + str(seed))
    for i in range(1, len(input_list)):      # Enumerate
        input_list[i] = seed + i
        print(input_list[i])
    print('Corrected list >> \n' + str(input_list))
    return input_list

def replace_file_names(correct_sequence_list):
    for filename, elem in zip(sorted_file_list, correct_sequence_list):
        print('Original filename %s') % (filename)
        filename_with_corrected_numbers = re.sub('\d+', filename, elem)
        print('Filename >> %s after re.sub') % (file_with_corrected_numbers)

sorted_file_list = put_files_in_sorted_list(DIRECTORY)
filename_int_list = get_list_of_ints(sorted_file_list)
correct_sequence_list = get_correct_sequence_numbering(filename_int_list)
replace_file_names(correct_sequence_list)
