#! python3
# tablePrinter2.py - #Attempt 4. Success :)

tableData = [['apples', 'oranges', 'cherries', 'banana'],
             ['Alice', 'Bob', 'Carol', 'David'],
             ['dogs', 'cats', 'moose', 'goose']]


def printTable():

    # Find the longest word. This will be used for calculating the appropriate spacing
    longestWidth = 0
    for wordList in tableData:
        for word in wordList:
            if len(word) > longestWidth:
                longestWidth = len(word)
    print('tableData length = ', str(len(tableData)))

    # Transpose the rows and colums
    transposed = []
    for i in range(0, len(tableData)):
        transposed.append([row[i] for row in tableData])
            
    # Print the newly ordered list with rjust spacing
    colWidth = (longestWidth + 1)
    for i in range(0, len(tableData)):
        line = transposed[i]
        for word in line:
            spacing = colWidth 
            print(word.rjust(spacing), end='')
        print()

printTable()


# Solved! This was a highly enjoyable challenge.
